# Generated by Django 6.0.4 on 2026-04-28 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chaType', models.CharField(choices=[('RN', 'Rong Cha'), ('DC', 'Dudh Cha'), ('MC', 'Masala Cha'), ('LC', 'Lebu Cha'), ('AC', 'Ada Cha')], max_length=2)),
            ],
        ),
    ]
