# Generated by Django 6.0.4 on 2026-04-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_application_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='chaType',
            field=models.CharField(choices=[('RC', 'Rong Cha'), ('DC', 'Dudh Cha'), ('MC', 'Masala Cha'), ('LC', 'Lebu Cha'), ('AC', 'Ada Cha')], max_length=2),
        ),
    ]
