# Generated by Django 6.0.4 on 2026-04-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_application_description_alter_application_chatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
