# Generated by Django 6.0.4 on 2026-04-30 21:13

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveBigIntegerField(help_text='Enter 6-digit pin code', validators=[student.models.validate_pin_length])),
                ('Zilla', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Cumilla', 'Cumilla'), ('Lakshmipur', 'Lakshmipur'), ('Noakhali', 'Noakhali'), ('Feni', 'Feni'), ('Chadpur', 'Chadpur'), ('Mymenshing', 'Mymenshing'), ('Bhola', 'Bhola'), ('Barishal', 'Barishal'), ('Patuakhali', 'Patuakhali'), ('Gazipur', 'Gazipur'), ('Narshingdi', 'Narshingdi'), ('Madaripur', 'Madaripur'), ('Noagaon', 'Noahgaon'), ('Pabna', 'Pabna'), ('Nator', 'Nator'), ('Narayanganj', 'Narayanganj'), ('Manikganj', 'Manikganj'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=100)),
                ('mobile', models.CharField(help_text='Enter 11 digit mobile number', max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')])),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
