# Generated by Django 6.0.4 on 2026-05-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Zilla',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Cumilla', 'Cumilla'), ('Lakshmipur', 'Lakshmipur'), ('Noakhali', 'Noakhali'), ('Feni', 'Feni'), ('Chadpur', 'Chadpur'), ('Mymenshing', 'Mymenshing'), ('Bhola', 'Bhola'), ('Barishal', 'Barishal'), ('Patuakhali', 'Patuakhali'), ('Gazipur', 'Gazipur'), ('Narshingdi', 'Narshingdi'), ('Madaripur', 'Madaripur'), ('Noagaon', 'Noahgaon'), ('Pabna', 'Pabna'), ('Nator', 'Nator'), ('Narayanganj', 'Narayanganj'), ('Manikganj', 'Manikganj'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Coxs Bazar', 'Coxs Bazar')], max_length=100),
        ),
    ]
